apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
  
  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686
    isDefault: false
    access: proxy
    editable: true
