receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp:
    protocols:
      grpc:
      http:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

  logging:
    loglevel: debug

  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

  spanmetrics:
    metrics_exporter: prometheus

  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: loki.resource.labels
        value: service_name

service:
  pipelines:
    traces:
      receivers: [ otlp, jaeger ]
      processors: [ spanmetrics, batch ]
      exporters: [ jaeger, logging ]
    # The exporter name in this pipeline must match the spanmetrics.metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [ otlp/spanmetrics ]
      exporters: [ prometheus, logging ]
    logs:
      receivers: [ otlp ]
      # processors: [ resource ]
      exporters: [ loki, logging ]
